### ISSUE TITLE
Consider adding some shapes?

### ISSUE THREAD

**Issue by 52manhua** [wdebeaum/svg-whiteboard#1]
Very good white-board application, thank you for providing us with such an interesting program.

I don't know if you've considered adding some shapes in the future. Or, more exactly, **labels with borders**, which looks more beautiful.
The style of the arrow can also be adjusted slightly, adding the adjusted knots to look softer.

Anyway, thank you.

**Comment by wdebeaum** [comment]
Simplicity is more of a design goal for this project than beauty is. And I think that automatically fitting borders or other node shapes around text objects in SVG is less simple than it might seem. You can always manually draw shapes of course. Or you might want to try OmniGraffle or Dia, if you want to do a boxes-and-arrows-style graph diagram. They both have large libraries of node shapes.

And I have no idea what you mean by "adding the adjusted knots to look softer". Could you explain that a bit more?

**Comment by 52manhua** [comment]
"adding the adjusted knots to look softer", I think I mean to replace straight lines with curves, maybe this requires more additional coding.

Yeah, this project is just fit for use than to show.

**Comment by wdebeaum** [comment]
I think you're probably talking about [composite Bézier curves](https://en.wikipedia.org/wiki/Composite_B%C3%A9zier_curve). SVG does have support for drawing these, but I think the user interface would be a bit complicated to make and use, and wouldn't really fit with the overall simplicity goal.
